#!/bin/bash
set -e

# Extract vanilla scripts
mkdir Source
echo "Extracting vanilla scripts..."
bsab.exe -e -f "*.pex" -o "Skyrim - Misc.bsa" ./Source/ >/dev/null
# Extract scripts from each CC BSA archive
echo "Extracting scripts from CC BSAs..."
mapfile -t bsas < <(ls ./cc*.bsa)
for bsa in "${bsas[@]}"
do
    bsab.exe -e -f "*.pex" -o "$bsa" ./Source/ >/dev/null
done
# De-compile all extracted scripts
echo "De-compiling scripts..."
cd ./Source/scripts
mapfile -t files < <(ls ./*.pex)
for file in "${files[@]}"
do
        echo "De-compiling $file"
        Champollion.exe "$file" >/dev/null
done
rm -f ./*.pex
# Format quest fragment scripts so the CK can read them
echo "Re-formatting quest scripts for the CK..."
mkdir temp
mv ./*.psc ./temp
cd temp
skyrim_format_fragments >/dev/null
# Move source scripts to /Source/scripts and clean up other directories
echo "Cleaning up..."
mv ./*.psc ../
cd ..
rmdir temp
cd ../..
# Extract USSEP and UCCCP scripts on top of vanilla scripts
echo "Extracting unofficial patch source scripts..."
bsab.exe -e -f "*.psc" -o Unofficial\ Skyrim\ Special\ Edition\ Patch.bsa ./ >/dev/null
bsab.exe -e -f "*.psc" -o Unofficial\ Skyrim\ Creation\ Club\ Content\ Patch.bsa ./ >/dev/null
